name: Build and deploy to registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
      fail-fast: false

    env:
      LATEST_PHP: '8.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/docker-symfony-php:${{ matrix.php-version }}
        # ajoute latest seulement si on est sur la version définie comme LATEST_PHP
      - name: Tag latest
        if: matrix.php-version == env.LATEST_PHP
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/docker-symfony-php:latest
